cmake CMakeLists.txt
cmake --install .
cmake --build .
copy src\pirmas.txt Debug\pirmas.txt
copy src\pirmas2.txt Debug\pirmas2.txt
copy src\pirmas3.txt Debug\pirmas3.txt
copy src\antras.txt Debug\antras.txt
copy src\antras2.txt Debug\antras2.txt
copy src\antras3.txt Debug\antras3.txt
copy src\trecias.txt Debug\trecias.txt
copy src\trecias2.txt Debug\trecias2.txt
copy src\trecias3.txt Debug\trecias3.txt
Debug\uzduotis1.exe